[tool.poetry]
name = "pypums"
version = "0.1.0"
description = "A Python package to explore IPUMS data."
authors = ["Francisco Javier Arceo <franciscojavierarceo@users.noreply.github.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
